// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object UrovoMessageInterfacePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Barcode information returned by a scan
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Barcode (
  val bytes: ByteArray? = null,
  val barcodeAsString: String? = null,
  val length: Long? = null,
  val code: String? = null,
  val type: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Barcode {
      val bytes = pigeonVar_list[0] as ByteArray?
      val barcodeAsString = pigeonVar_list[1] as String?
      val length = pigeonVar_list[2] as Long?
      val code = pigeonVar_list[3] as String?
      val type = pigeonVar_list[4] as Long?
      return Barcode(bytes, barcodeAsString, length, code, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bytes,
      barcodeAsString,
      length,
      code,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Barcode
    return UrovoMessageInterfacePigeonUtils.deepEquals(this.bytes, other.bytes) && UrovoMessageInterfacePigeonUtils.deepEquals(this.barcodeAsString, other.barcodeAsString) && UrovoMessageInterfacePigeonUtils.deepEquals(this.length, other.length) && UrovoMessageInterfacePigeonUtils.deepEquals(this.code, other.code) && UrovoMessageInterfacePigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UrovoMessageInterfacePigeonUtils.deepHash(this.bytes)
    result = 31 * result + UrovoMessageInterfacePigeonUtils.deepHash(this.barcodeAsString)
    result = 31 * result + UrovoMessageInterfacePigeonUtils.deepHash(this.length)
    result = 31 * result + UrovoMessageInterfacePigeonUtils.deepHash(this.code)
    result = 31 * result + UrovoMessageInterfacePigeonUtils.deepHash(this.type)
    return result
  }
}

/**
 * this represent a type of barcode (this is only used for communicating
 * with the native code i.e. kotlin)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Code (
  /**the format id */
  val id: Long,
  /**the format type of the barcode */
  val type: String,
  /**is the barcode supported by the scanner */
  val supported: Boolean,
  /**is the type enabled */
  val enabled: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Code {
      val id = pigeonVar_list[0] as Long
      val type = pigeonVar_list[1] as String
      val supported = pigeonVar_list[2] as Boolean
      val enabled = pigeonVar_list[3] as Boolean
      return Code(id, type, supported, enabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      supported,
      enabled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Code
    return UrovoMessageInterfacePigeonUtils.deepEquals(this.id, other.id) && UrovoMessageInterfacePigeonUtils.deepEquals(this.type, other.type) && UrovoMessageInterfacePigeonUtils.deepEquals(this.supported, other.supported) && UrovoMessageInterfacePigeonUtils.deepEquals(this.enabled, other.enabled)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UrovoMessageInterfacePigeonUtils.deepHash(this.id)
    result = 31 * result + UrovoMessageInterfacePigeonUtils.deepHash(this.type)
    result = 31 * result + UrovoMessageInterfacePigeonUtils.deepHash(this.supported)
    result = 31 * result + UrovoMessageInterfacePigeonUtils.deepHash(this.enabled)
    return result
  }
}
private open class urovo_message_interfacePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Barcode.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Code.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Barcode -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is Code -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val urovo_message_interfacePigeonMethodCodec = StandardMethodCodec(urovo_message_interfacePigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UrovoMessageInterface {
  fun openScanner()
  fun closeScanner()
  fun getScannerStat(callback: (Result<Boolean>) -> Unit)
  fun getDeviceManufacture(callback: (Result<String>) -> Unit)
  fun getDeviceModel(callback: (Result<String>) -> Unit)
  fun startScanning()
  fun stopScanning()
  fun getTimeOut(callback: (Result<Long>) -> Unit)
  fun setTimeOut(timeout: Long)
  fun getSoundMode(callback: (Result<Long?>) -> Unit)
  fun setSoundMode(mode: Long)
  fun isVibrationEnabled(callback: (Result<Boolean>) -> Unit)
  fun enableVibration()
  fun disableVibration()
  fun isTriggerEnabled(callback: (Result<Boolean>) -> Unit)
  fun enableTrigger()
  fun disableTrigger()
  fun getScanMode(callback: (Result<Long?>) -> Unit)
  fun setScanMode(mode: Long)
  fun getCodes(callback: (Result<List<Code>>) -> Unit)
  fun getCode(codeId: Long, callback: (Result<Code?>) -> Unit)
  fun enableCode(codeId: Long)
  fun enableAllCodes()
  fun disableCode(codeId: Long)
  fun disableAllCodes()
  fun resetScanner()

  companion object {
    /** The codec used by UrovoMessageInterface. */
    val codec: MessageCodec<Any?> by lazy {
      urovo_message_interfacePigeonCodec()
    }
    /** Sets up an instance of `UrovoMessageInterface` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UrovoMessageInterface?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.openScanner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openScanner()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.closeScanner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.closeScanner()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.getScannerStat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getScannerStat{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.getDeviceManufacture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceManufacture{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.getDeviceModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceModel{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.startScanning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startScanning()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.stopScanning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScanning()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.getTimeOut$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getTimeOut{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.setTimeOut$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setTimeOut(timeoutArg)
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.getSoundMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getSoundMode{ result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.setSoundMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setSoundMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.isVibrationEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isVibrationEnabled{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.enableVibration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.enableVibration()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.disableVibration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disableVibration()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.isTriggerEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isTriggerEnabled{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.enableTrigger$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.enableTrigger()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.disableTrigger$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disableTrigger()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.getScanMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getScanMode{ result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.setScanMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setScanMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.getCodes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCodes{ result: Result<List<Code>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.getCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val codeIdArg = args[0] as Long
            api.getCode(codeIdArg) { result: Result<Code?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(UrovoMessageInterfacePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.enableCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val codeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.enableCode(codeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.enableAllCodes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.enableAllCodes()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.disableCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val codeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.disableCode(codeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.disableAllCodes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disableAllCodes()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.urovo_scanning_package.UrovoMessageInterface.resetScanner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resetScanner()
              listOf(null)
            } catch (exception: Throwable) {
              UrovoMessageInterfacePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class urovo_message_interfacePigeonStreamHandler<T>(
    val wrapper: urovo_message_interfacePigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface urovo_message_interfacePigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/** */
abstract class OnBarcodeChangedStreamHandler : urovo_message_interfacePigeonEventChannelWrapper<Barcode> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnBarcodeChangedStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.urovo_scanning_package.UrovoBarcodeInterface.onBarcodeChanged"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = urovo_message_interfacePigeonStreamHandler<Barcode>(streamHandler)
      EventChannel(messenger, channelName, urovo_message_interfacePigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from urovo_message_interfacePigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<Barcode>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class OnBarcodeImageChangedStreamHandler : urovo_message_interfacePigeonEventChannelWrapper<ByteArray> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnBarcodeImageChangedStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.urovo_scanning_package.UrovoBarcodeInterface.onBarcodeImageChanged"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = urovo_message_interfacePigeonStreamHandler<ByteArray>(streamHandler)
      EventChannel(messenger, channelName, urovo_message_interfacePigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from urovo_message_interfacePigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<ByteArray>) {}

override fun onCancel(p0: Any?) {}
}
      
